### ISSUE TITLE
Create a Logo/Title

### ISSUE THREAD

**Issue by AustinB12** [AustinB12/jacobs-band#1]
The site should have a logo that corresponds to the band!

**Comment by AustinB12** [comment]
I assigned this issue to you because you said you had a logo you wanted to add. 🙂

**Comment by jacobadams111** [comment]
Ah of course its not letting me sign into adobe now. I'm gonna see if I can use Ambria's account still lol. But I will add the logo as soon as I can.

**Comment by AustinB12** [comment]
Oh no! You're not going to lose your work, are you?

**Comment by jacobadams111** [comment]
Nah, as long as I can sign in to adobe from a valid account it will be there.

**Comment by AustinB12** [comment]
Okay, cool cool
